name: Read hello.txt

on:
  push:
    branches:
      - main  # Trigger workflow only on pushes to main branch

jobs:
  read-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read hello.txt
        run: |
          echo "📄 Content of hello.txt:"
          cat hello.txt
